#pragma once

#include "D3Devices.h"
#include "Transpose_mk2.h"
#include "IndexBuffer.h"
#include "IndexBuffer_mk2.h"
#include "InputLayout.h"
#include "VertexBuffer.h"
#include "Effect.h"
#include "RainbowBoxScript.h"
#include "Renderor.h"
#include "FbxLoad.h"
#include "ConstBufferTutorial05.h"
#include "ConstBufferTutorial06.h"
#include "AnimateRotateY.h"
#include "AnimateRotateZ.h"
#include "LightBox1Script.h"
#include "VertexResource.h"
#include "Devices.h"
#include "GetFbxMeshNol.h"
//#include "GetFbxMesh.h"
//#include "Texture.h"
//#include "ConstBufferLight.h"
//#include "Transpose.h"
//#include "CameraPtr.h"

// 스크립트

#include "GridScript.h"
#include "ColoredBox2Script.h"
#include "ScriptTutorial06.h"
//#include "BoxScript.h"
//#include "TriangleScript.h"
