#pragma once

#include "D3Devices.h"
#include "Transpose.h"
#include "Transpose_mk2.h"
#include "CameraPtr.h"
#include "IndexBuffer.h"
#include "IndexBuffer_mk2.h"
#include "InputLayout.h"
#include "VertexBuffer.h"
#include "Effect.h"
#include "Texture.h"
#include "RainbowBoxScript.h"
#include "Renderor.h"
#include "FbxLoad.h"
#include "ConstBufferWVP.h"

#include "GridScript.h"
#include "BoxScript.h"
#include "TriangleScript.h"